// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybdlstbaedwenpcdeerf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZGxzdGJhZWR3ZW5wY2RlZXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTA5MjIsImV4cCI6MjA2MTMyNjkyMn0.ydqMKNL5W4LwD3q95jL_pkpmRbho1nPrLbSLurW970I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);